Problem: Building distributable app fails
It seems `electron-builder` is expecting a default of `index.js`. When we
made the web version we renamed `index.js` to `electron-index.js`.

See: dc6f0bb6d0949c9026cca31df99583bac18706f5

When trying to build the app it now results in an error message like:

```
Error: Application entry file "index.js" in the
"/.../exosphere/dist/mac/Exosphere.app/Contents/Resources/app.asar" does not exist. Seems like
a wrong configuration
```

Solution: Add a parameter `-c.extraMetadata.main` set to `electron-index.js`
when calling `electron-builder`.